services:
  oc_autonomo:
    build:
      context: .
    container_name: oc_autonomo
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    command: ["python", "app.py"]
